### PR TITLE
added settings to import and load new sound theme from zip file 

### PR DESCRIPTION
**Pull request by adil-s**
I'm trying to address the issue mention in the repo read me file with this PR. 
made following changes:
* added new setting category under nvda menu >preferences > unspoken setting 
* default add-on sounds are moved into  default theme 
* under unspoken setting, you can select desired sound theme 
* added import sound theme button to load sound theme from a zip file 
to create a sound theme: 
* find some sound sample 
* use  any audio editor of your choice and convert the sound sample 
* the output file format must be .  wav 
* output sound file channel must be mono (1 channel) 
* rename the output files 
* example: a.wav to link.wav 
* create a new folder with your sound theme name 
* move your all sound files into newly created folder 
* zip the folder and import into unspoken 
the PR needs still some edits so, I would urge you to give me some feetback  so that I can keep working on it. 
checkout the attached sound theme created from default theme.

[windows theme.zip](https://github.com/SeanTolstoyevski/unspokenPy3/files/5155360/windows.theme.zip)

### CODE REVIEW

**Comment by SeanTolstoyevski** [comment]
Many thanks for this first PR.

I ran the tests. Everything seems successful.

I'm going to merge it now.

**Comment by SeanTolstoyevski** [comment]
I will not close the PR.

Some style differences appear.
And some complex code structures.

We can discuss them here.

**Comment by adil-s** [comment]
can I know what formatter do you use to format your source code?
can you share your formatter configuration so we can have same code style? 
by complex code, what part of the code is you are refering to? 
if possible, I would try to simplify as much as I can.

**Comment by SeanTolstoyevski** [comment]
In Windows, line end breaks are encoded with "CRLF" by default.
Could you replace it with "LF"?

This allows us to better understand the lines with NVDA.

**Comment by SeanTolstoyevski** [comment]
Can you add this to gitignore?

`* text eol = lf`

**Pull request merged**
